/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgAsideControlOff = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={20} height={68} fill="none" {...props}>
    <g opacity={0.9}>
      <path
        fill="#2B3139"
        d="M20 0 2.359 7.939A4 4 0 0 0 0 11.586v44.828a4 4 0 0 0 2.359 3.647L20 68z"
      />
      <path
        stroke="#B7BDC6"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.67}
        d="m7.5 39 5-5-5-5"
      />
    </g>
  </svg>
);
export default SvgAsideControlOff;
