/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgCameraDisabledSingleColorIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" {...props}>
    <g
      stroke="#B7BDC6"
      strokeLinecap="round"
      strokeWidth={1.333}
      clipPath="url(#camera-disabled-single-color-icon_svg__a)"
    >
      <path
        strokeLinejoin="round"
        d="m10 6.667 3.035-1.518a.667.667 0 0 1 .965.596v4.51a.667.667 0 0 1-.965.596L10 9.333zM8.667 4H3.333C2.597 4 2 4.597 2 5.333v5.334C2 11.403 2.597 12 3.333 12h5.334C9.403 12 10 11.403 10 10.667V5.333C10 4.597 9.403 4 8.667 4"
      />
      <path d="M2.277 1.333 14.534 13.59" />
    </g>
    <defs>
      <clipPath id="camera-disabled-single-color-icon_svg__a">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgCameraDisabledSingleColorIcon;
