/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgMemberListIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" {...props}>
    <path
      stroke="#fff"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M7.777 9.26a2.963 2.963 0 1 0 0-5.927 2.963 2.963 0 0 0 0 5.926M12.964 3.43a2.963 2.963 0 0 1 0 5.74m3.703 7.497v-1.482a2.96 2.96 0 0 0-2.222-2.852M3.334 16.667v-1.482a2.963 2.963 0 0 1 2.963-2.963H9.26a2.963 2.963 0 0 1 2.963 2.963v1.482z"
    />
  </svg>
);
export default SvgMemberListIcon;
