/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgMicDisabledSingleColorIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" {...props}>
    <path
      stroke="#B7BDC6"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="M10 3.333a2 2 0 1 0-4 0v3.334a2 2 0 1 0 4 0zM3.334 6.667a4.667 4.667 0 0 0 4.667 4.666m0 0a4.667 4.667 0 0 0 4.667-4.666M8 11.333V14m-2.667 0h5.334"
    />
    <path
      stroke="#B7BDC6"
      strokeLinecap="round"
      strokeWidth={1.333}
      d="M2.277 1.333 14.534 13.59"
    />
  </svg>
);
export default SvgMicDisabledSingleColorIcon;
