/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgSendMessage = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} fill="none" {...props}>
    <path
      stroke="#707A8A"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="m3.5 19.5.799-3.882A8.984 8.984 0 0 1 6.397 3.963a8.996 8.996 0 0 1 14.569 6.246 8.984 8.984 0 0 1-7.003 9.552 9 9 0 0 1-6.267-.884z"
    />
    <circle cx={8} cy={11} r={0.5} fill="#fff" stroke="#707A8A" />
    <circle cx={12} cy={11} r={0.5} fill="#fff" stroke="#707A8A" />
    <circle cx={16} cy={11} r={0.5} fill="#fff" stroke="#707A8A" />
  </svg>
);
export default SvgSendMessage;
